#!/bin/sh

# SPDX-FileCopyrightText: 2023 Joonas Rautiola <joinemm@pm.me>
# SPDX-License-Identifier: MPL-2.0
# https://git.joinemm.dev/miso-bot

pip-compile requirements.in > requirements.txt --resolver=backtracking
pip-compile dev-requirements.in > dev-requirements.txt --resolver=backtracking

