#!/bin/sh

# SPDX-FileCopyrightText: 2023 Joonas Rautiola <joinemm@pm.me>
# SPDX-License-Identifier: MPL-2.0
# https://git.joinemm.dev/miso-bot

reuse addheader --copyright="Joonas Rautiola <joinemm@pm.me>" --license="MPL-2.0" --template="header.jinja2" $@
